<?php
class JConfig {
	var $offline = '0';
	var $editor = 'wysiwygPro3';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '1';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'B4QASGi0RcOl4ly7';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = '/var/www/viswanathlab.org/logs';
	var $tmp_path = '/var/www/viswanathlab.org/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '-5';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'vlab';
	var $db = 'vlab';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'health_communication@dfci.harvard.edu';
	var $fromname = 'Viswanath Lab';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '90';
	var $session_handler = 'database';
	var $password = 'vlabplease';
	var $sitename = 'Viswanath Lab';
	var $MetaDesc = 'This web site is a resource for researchers, students, and practitioners interested in health communication, particularly as it relates to health disparities.';
	var $MetaKeys = '19th monograph of the NCI\'s Tobacco Control Series,Cancer communications,Center for Community Based Research,Click to Connect,Communication,Communication inequalities,Communication internship,Communication science,Communications Laboratory,Community-based participatory research,Dana-Farber Cancer Institute,Dana-Farber/Harvard Cancer Center,Digital divide,Digital Inequalities,ECHO Lab,eHealth,Emergency preparedness,Enhancing Communications for Health Outcomes Laboratory,Harvard School of Public Health,Health,Health Behavior and Health Education: Theory, Research and Practice,Health Communication,Health Communications Core,Health Disparities,Health information,Health Journalists,Health Literacy,Inequalities,Information seeking,K. Viswanath,
Knowledge networks,Knowledge translation,Mass media,Mass Media, Social Control, and Social Change: A Macrosocial Perspective,MassCONECT,PLANET MassCONECT,Public Health,Public Health Campaigns,Risk communication,Social capital,Social networking,The International Encyclopedia of Communication,Tobacco Research,TReND,Usability testing,Vish Viswanath,Viswanath Lab,Web based interventions';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
}
?>
